services:
  backend:
    build:
      context: ./backend
    command: bash -c "bundle exec rails s -b '0.0.0.0' -p 3333"
    volumes:
      - ./backend:/backend
    ports:
      - 3333:3333
    tty: true
    stdin_open: true

  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./frontend
    command: "npm run dev"
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
